cloudera-labs/cloudera-deploy

quickstart.sh
Add support to specify IMAGE_VER when running quickstart
Allow download of profile template directly from repo when running quickstart.sh without cloning repo
Improve console status messages during quickstart execution
=> Modify quickstart so it can be run directly from repo without checkout

roles/cloudera_deploy/tasks/init.yml
Clean up admin password initial checks to only require minimum of 2 chars by default
Remove admin_password from early globals setup, and reserve for final init calls to avoid excessive logging
Add init_call_cdp_public to test if top level keys have been set to request CDP Public actions which may require password enforcement
Set regex enforcement of CDP Public Password to 8-64 chars, 1 special, 1 number, 1 capital if CDP Public is being called
=> Situationally check and enforce CDP Public Password requirements

quickstart.sh
Set aws cli default output to json overriding user profile default, allows Ansible to expect aws cli output in json format for parsing
Fixes #7
=> Set aws cli default output to json overriding user profile default

cluster.yml
requires user accounts to precede tls creation for key ACLs and then requires tls to precede RDBMS creation).
=> Change ordering of roles to enable database TLS

readme.adoc
Added instructions for upgrading cloudera-deploy when it is checked out using git
Added option to use the quickstart.sh script without checkout
Added sections on checking credentials before attempting an Execution
Various other tweaks and revisions
=> Readme Updates

readme.adoc
The current URL specified links to the file as viewed in the GitHub UI, calling `curl` on that will download HTML code, not a formatted YAML file.
Using the current value actually hits a 302 redirect:
```
$ curl https://github.com/cloudera-labs/cldr-runner/tree/main/payload/deps/ansible.yml     --output out.txt
$ cat out.txt 
<html><body>You are being <a href="https://github.com/cloudera-labs/cldr-runner/blob/main/payload/deps/ansible.yml">redirected</a>.</body></html>
```
Using the redirect value results in HTML:
```
$ curl https://github.com/cloudera-labs/cldr-runner/blob/main/payload/deps/ansible.yml     --output out.txt
$ head -20 out.txt 
<!DOCTYPE html>
<html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark">
<head>
<meta charset="utf-8">
<link …
```
=> Use raw github content for ansible galaxy requirements

roles/cloudera_deploy/tasks/init.yml
Dependent on https://github.com/cloudera-labs/cloudera.exe/pull/20
Dependent on https://github.com/cloudera-labs/cloudera.cloud/pull/17
Dependent on https://github.com/cloudera-labs/cdpy/pull/21
Add df key to cloud and cdp public triggers so they are run when df is called solo
=> Changes for DF-beta

roles/cloudera_deploy/tasks/init.yml
Do not validate name_prefix when running a teardown, the user may have reasons for wanting to purge an arbitrary namespace
Validate SSH Private  Key File permissions to handle edge case where a user has misconfigured their ssh dir and Ansible will refuse to connect
=> Teardown improvements

roles/cloudera_deploy/tasks/init.yml
Fix CDP_PROFILE and AWS_PROFILE propagation to globals so that it can be set within any Definition file and work as expected.
Include sanity check of purge keyword to ensure it is a proper boolean and not a bare key.
=> Minor Fixes

roles/cloudera_deploy/defaults/basic_cluster.yml, roles/cloudera_deploy/tasks/populate_download_mirror.yml
Hotfix for broken URL for CDH parcels repo. Also updated the `cloudera_manager_version` variable to the latest version.
We could use the value `latest` in the parcels repo URL but this doesn't seem possible for the CM version.  Also, we figured it's better to stick with known and tested versions as these are default values.  So I've went with hardcoded version numbers for both CDH and CM.
A note about commit https://github.com/cloudera-labs/cloudera-deploy/pull/55/commits/db7a5a7b62099b1e67c82d13bf001704fa36647c:
* When testing with a new set of parcels the Cloudera Deploy task to `Sync downloaded Files paths to S3 cache bucket` fails because of missing Python concurrent.futures module. 
* Doing a bit more digging, this task is running on the Utility VM created in AWS. These VMs are …
=> Update to parcels url and cm version

roles/cloudera_deploy/defaults/basic_cluster.yml, roles/cloudera_deploy/tasks/populate_download_mirror.yml
Reverts cloudera-labs/cloudera-deploy#55 in order to create a hotfix into both `main` and `devel`
=> Revert "Update to parcels url and cm version"

roles/cloudera_deploy/defaults/basic_cluster.yml, roles/cloudera_deploy/tasks/populate_download_mirror.yml
Hotfix for broken URL for CDH parcels repo. Also updated the `cloudera_manager_version` variable to the latest version.
We could use the value latest in the parcels repo URL but this doesn't seem possible for the CM version. Also, we figured it's better to stick with known and tested versions as these are default values. So I've went with hardcoded version numbers for both CDH and CM.
A note about commit https://github.com/cloudera-labs/cloudera-deploy/commit/1366d8d19ee49c119ea7b3ba0ba458bdedbe7867
* When testing with a new set of parcels the Cloudera Deploy task to `Sync downloaded Files paths to S3 cache bucket` fails because of missing Python concurrent.futures module.
* Doing a bit more digging, this task is running on the Utility VM created in AWS. These VMs are CentOS 7 images and …
=> Update to parcels url and cm version take 2

roles/cloudera_deploy/tasks/init.yml
Move admin_password check after composition of definition files to allow the user to set it in any included file
=> Move admin_password check

readme.adoc
Fixes #58 
Signed-off-by: Webster Mudge <wmudge@cloudera.com>
=> Update documentation for Docker Engine install warning

examples/cdf/definition.yml
Dependencies:
https://github.com/cloudera-labs/cloudera.exe/pull/47
https://github.com/cloudera-labs/cloudera.cloud/pull/31
https://github.com/cloudera-labs/cdpy/pull/30
Update the cloudera-deploy CDF example definition to have the GA parameters by default
=> Update DFX implementation for GA

roles/cloudera_deploy/tasks/init.yml
Assess purge as bool before checking for true false to allow extra var submission with simple strings
=> improve purge boolean test

quickstart.sh, readme.adoc
Correct some Error and logging messages in quickstart.sh
Add 'CLDR_PYTHON_PATH' option to quickstart.sh, which may be set to the mounted path of cdpy, e.g. /runner/project/cdpy/src
Correct usage of inventory_static.ini in readme
=> Add developer mode option for cdpy

cluster.yml, roles/cloudera_deploy/defaults/main.yml, roles/cloudera_deploy/tasks/init.yml, roles/cloudera_deploy/tasks/inject_download_mirror.yml, roles/cloudera_deploy/tasks/populate_download_mirror.yml, roles/cloudera_deploy/tasks/prepare_download_mirror.yml
Change cloudera-deploy defaults to el7, but allow el8 to be specified and recognised
Update utility VM used for download mirror to function correctly with el7 or el8 OS
Add default_cluster tag to cluster.yml playbook CM Agent heartbeat test to avoid obscure failures
=> Add EL8 support to Cloudera Collections

main.yml, readme.adoc, roles/cloudera_deploy/defaults/main.yml, roles/cloudera_deploy/tasks/auto_terraform_state.yml, roles/cloudera_deploy/tasks/init.yml
Code changes and doc update for Terraform deployment of cloud resources.
Changes done in conjunction with this cloudera.exe PR: https://github.com/cloudera-labs/cloudera.exe/pull/56
=> Add Terraform deployment engine for cloud resources

quickstart.sh
Two-line fix for `quickstart.sh`; see #74.
=> quickstart.sh: Fix unintentional command execution.

roles/cloudera_deploy/tasks/init.yml
Introduce a `cdp_region` variable that can be used to specify the CDP Control Plane region.
Changes done in conjunction with this cloudera.exe PR: https://github.com/cloudera-labs/cloudera.exe/pull/91
=> Support the use of other CDP control planes

main.yml, readme.adoc, roles/cloudera_deploy/tasks/auto_terraform_state.yml, roles/cloudera_deploy/tasks/init.yml
After reviewing the Terraform variables with @wmudge, we agreed that changing the Terraform global variables to be a dictionary gives a better structure to the inputs. Changes done in conjunction with [cloudera.exe PR#100](https://github.com/cloudera-labs/cloudera.exe/pull/100)
An example of the Terraform-related entries in the Cloudera-Deploy definition file following this change are shown below.
```yaml
infra_deployment_engine: terraform
terraform:
state_storage: remote_s3
auto_remote_state: True
remote_state_bucket: example-state-bucket-config
remote_state_lock_table: example-state-lock-table-config
```
Signed-off-by: Jim Enright <jenright@cloudera.com>
=> Convert terraform related global variables to a dictionary

examples/cdf/application.yml, examples/cdf/definition.yml
Dependent on:
cloudera-labs/cdpy#40
cloudera-labs/cloudera.cloud#45
cloudera-labs/cloudera.exe#82
Update CDF Example to include deploying a basic DFX Flow for experimentation
=> Df deployments

quickstart.sh
Signed-off-by: Webster Mudge <wmudge@cloudera.com>
=> Update image selection variables

cluster.yml
This change removes the ca_certs role from cluster.yml.
This functionality has been moved as part of the changes required to fix FreeIPA.
Note: This PR must be merged with the corresponding cloudera.cluster PR of the same name
=> 2021 07 freeipa dep fix

roles/cloudera_deploy/tasks/distribute_facts_to_inventory.yml
Allows to use variables in definition_file, e.g. : 
```yaml
clusters:
- name: "{{ cdp_cluster_name }}"
type: base
services: "{{ cdp_services }}"
databases: "{{ cdp_databases }}"
configs: "{{ fresh_install_configs }}"
host_templates: "{{ cdp_host_templates }}"
...
```
=> #94 Load definition_file with include vars

quickstart.sh
Update the `quickstart.sh` to pin `cldr-runner` and `cloudera-deploy` to v1.7.4 and v1.7.1 respectively. This fix should allow one to checkout this branch and run the legacy `quickstart.sh` without other updates.
=> Update quickstart.sh to pin cldr-runner and cloudera-deploy

README.md
Need Python 3.9 or higher for ansible-navigator (on OSX, at least)
=> Update README for minimum Python version 

private-cloud/base/aws-iaas/base_teardown.yml, private-cloud/base/aws-iaas/definition.yml
Fix ipa user search group & add base_teardown
Signed-off-by: Chuck Levesque <clevesque@cloudera.com>
=> Fix ipa user search group & add base_teardown
